FROM almalinux:9
ARG course="DevOps with AWS" \
    trainer="siva" \
    duration="1hr"

RUN echo "Course: $course" && \
    echo "Trainer: $trainer" && \
    echo "Duration: $duration"
CMD ["sleep","100"]